apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2 
kind: Deployment 
metadata: 
  name: hello-world 
spec: 
  selector: 
    matchLabels: 
      app: hello-world 
  replicas: 2 # tells deployment to run 2 pods matching the template 
  template:
    metadata: 
      labels: 
        app: hello-world 
    spec: 
      containers: 
      - name: hello-world 
        image: macdoc1/hello-world-python:0.0.2.RELEASE
        ports: 
        - containerPort: 5000 
--- 
# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service  
kind: Service 
apiVersion: v1 
metadata: 
  name: hello-world 
spec: 
  selector: 
    app: hello-world 
  ports: 
  - protocol: TCP 
    port: 5000 
    targetPort: 5000 
  type: LoadBalancer
